### PR TITLE
Error analysing from logs

### LINKED ISSUE #6: Idea: Error analysis
- Responds to common errors, like address in use errors
- Tells people when errors probably aren't caused by Geyser (when `org.geysermc` isn't mentioned in the stack trace)
- Send a link to the file and line the error comes from, to helps devs troubleshoot the problem
- Searches existing GitHub issues for the error

### PR DESCRIPTION
**Pull request by rtm516**
Close #6 

TODO:
- [x] Show solutions to known issues
- [x] Show other unknown Geyser errors
- [x] Fix links for code references not working outside of connector
- [x] Fix multiple checks caused by async calls

### CODE REVIEW

File: bot_modules/error_analyse/index.js [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+
+      // Build the exception title and see if we have a fix
+      const exceptionTitle = group.exception.exception + ': ' + group.exception.message
+      const exeption = configExceptions.find(x => exceptionTitle.startsWith(x.error))
+
+      // Check we dont already know about the exception in this log and add it
+      if (exeption && !embed.fields.find(x => x.name === exceptionTitle)) {
+        embed.addField(exceptionTitle, exeption.message)
+      }
+    }
```
Comment (Heath123) [inline bot_modules/error_analyse/index.js:88]: Wouldn't it make sense to check if the stack trace doesn't include `org.geysermc` and tell them that it probably isn't related to Geyser? My other issue was having a link to the line where it happened to help with debugging

**Review by Heath123 — CHANGES_REQUESTED** [review]

File: bot_modules/error_analyse/index.js [hunk 2]
```diff
@@ -0,0 +1,162 @@
...
+  embed.setTitle('Found errors in the log!')
+  embed.setDescription('See below for details and possible fixes')
+  embed.setColor(0xff0000)
+
+  // If we have no fields set the description acordingly
+  if (embed.fields.length <= 0) {
+    if (geyserException) {
+      embed.setDescription('We don\'t currently have automated responses for the detected errors!')
+    } else {
+      embed.setDescription('The errors you have are not Geyser related or caused!')
```
Comment (Heath123) [inline bot_modules/error_analyse/index.js:155]: Geyser could probably cause other errors because of conflicts, so maybe say they _probably_ aren't related but could be?

**Review by Heath123 — CHANGES_REQUESTED** [review]

**Review by Heath123 — APPROVED** [review]
